// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OlympicGames.Models;

namespace OlympicGames.Migrations
{
    [DbContext(typeof(TeamContext))]
    [Migration("20220307013049_UpdateContext")]
    partial class UpdateContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("OlympicGames.Models.Game", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = "wint",
                            Name = "Winter Olympics"
                        },
                        new
                        {
                            GameId = "sum",
                            Name = "Summer Olympics"
                        },
                        new
                        {
                            GameId = "para",
                            Name = "Paralympics"
                        },
                        new
                        {
                            GameId = "y",
                            Name = "Youth Olympic Games"
                        });
                });

            modelBuilder.Entity("OlympicGames.Models.Sport", b =>
                {
                    b.Property<string>("SportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportId");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            SportId = "cur",
                            Name = "Curling/Indoor"
                        },
                        new
                        {
                            SportId = "bob",
                            Name = "Bobsleigh/Outdoor"
                        },
                        new
                        {
                            SportId = "div",
                            Name = "Diving/Indoor"
                        },
                        new
                        {
                            SportId = "road",
                            Name = "Road Cycling/Outdoor"
                        },
                        new
                        {
                            SportId = "arch",
                            Name = "Archery/Indoor"
                        },
                        new
                        {
                            SportId = "can",
                            Name = "Canoe Sprint/Outdoor"
                        },
                        new
                        {
                            SportId = "break",
                            Name = "Breakdancing/Indoor"
                        },
                        new
                        {
                            SportId = "skate",
                            Name = "Skateboarding/Outdoor"
                        });
                });

            modelBuilder.Entity("OlympicGames.Models.Team", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LogoImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TeamId");

                    b.HasIndex("GameId");

                    b.HasIndex("SportId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = "canada",
                            GameId = "wint",
                            LogoImage = "canada.png",
                            Name = "Canada",
                            SportId = "cur"
                        },
                        new
                        {
                            TeamId = "sweden",
                            GameId = "wint",
                            LogoImage = "sweden.png",
                            Name = "Sweden",
                            SportId = "cur"
                        },
                        new
                        {
                            TeamId = "gb",
                            GameId = "wint",
                            LogoImage = "gb.png",
                            Name = "Great Britain",
                            SportId = "cur"
                        },
                        new
                        {
                            TeamId = "jamaica",
                            GameId = "wint",
                            LogoImage = "jamaica.png",
                            Name = "Jamaica",
                            SportId = "bob"
                        },
                        new
                        {
                            TeamId = "italy",
                            GameId = "wint",
                            LogoImage = "italy.png",
                            Name = "Italy",
                            SportId = "bob"
                        },
                        new
                        {
                            TeamId = "japan",
                            GameId = "wint",
                            LogoImage = "japan.png",
                            Name = "Japan",
                            SportId = "bob"
                        },
                        new
                        {
                            TeamId = "germany",
                            GameId = "sum",
                            LogoImage = "germany.png",
                            Name = "Germany",
                            SportId = "div"
                        },
                        new
                        {
                            TeamId = "china",
                            GameId = "sum",
                            LogoImage = "china.png",
                            Name = "China",
                            SportId = "div"
                        },
                        new
                        {
                            TeamId = "mexico",
                            GameId = "sum",
                            LogoImage = "mexico.png",
                            Name = "Mexico",
                            SportId = "div"
                        },
                        new
                        {
                            TeamId = "brazil",
                            GameId = "sum",
                            LogoImage = "brazil.png",
                            Name = "Brazil",
                            SportId = "road"
                        },
                        new
                        {
                            TeamId = "netherlands",
                            GameId = "sum",
                            LogoImage = "netherlands.png",
                            Name = "Netherlands",
                            SportId = "road"
                        },
                        new
                        {
                            TeamId = "usa",
                            GameId = "sum",
                            LogoImage = "usa.png",
                            Name = "USA",
                            SportId = "road"
                        },
                        new
                        {
                            TeamId = "thailand",
                            GameId = "para",
                            LogoImage = "thailand.png",
                            Name = "Thailand",
                            SportId = "arch"
                        },
                        new
                        {
                            TeamId = "uruguay",
                            GameId = "para",
                            LogoImage = "uruguay.png",
                            Name = "Uruguay",
                            SportId = "arch"
                        },
                        new
                        {
                            TeamId = "ukraine",
                            GameId = "para",
                            LogoImage = "ukraine.png",
                            Name = "Ukraine",
                            SportId = "arch"
                        },
                        new
                        {
                            TeamId = "austria",
                            GameId = "para",
                            LogoImage = "austria.png",
                            Name = "Austria",
                            SportId = "can"
                        },
                        new
                        {
                            TeamId = "pakistan",
                            GameId = "para",
                            LogoImage = "pakistan.png",
                            Name = "Pakistan",
                            SportId = "can"
                        },
                        new
                        {
                            TeamId = "zimbabwe",
                            GameId = "para",
                            LogoImage = "zimbabwe.png",
                            Name = "Zimbabwe",
                            SportId = "can"
                        },
                        new
                        {
                            TeamId = "france",
                            GameId = "y",
                            LogoImage = "france.png",
                            Name = "France",
                            SportId = "break"
                        },
                        new
                        {
                            TeamId = "cyprus",
                            GameId = "y",
                            LogoImage = "cyprus.png",
                            Name = "Cyprus",
                            SportId = "break"
                        },
                        new
                        {
                            TeamId = "russia",
                            GameId = "y",
                            LogoImage = "russia.png",
                            Name = "Russia",
                            SportId = "break"
                        },
                        new
                        {
                            TeamId = "finland",
                            GameId = "y",
                            LogoImage = "finland.png",
                            Name = "Finland",
                            SportId = "skate"
                        },
                        new
                        {
                            TeamId = "slovakia",
                            GameId = "y",
                            LogoImage = "slovakia.png",
                            Name = "Slovakia",
                            SportId = "skate"
                        },
                        new
                        {
                            TeamId = "portugal",
                            GameId = "y",
                            LogoImage = "portugal.png",
                            Name = "Portugal",
                            SportId = "skate"
                        });
                });

            modelBuilder.Entity("OlympicGames.Models.Team", b =>
                {
                    b.HasOne("OlympicGames.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId");

                    b.HasOne("OlympicGames.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId");

                    b.Navigation("Game");

                    b.Navigation("Sport");
                });
#pragma warning restore 612, 618
        }
    }
}
